name: send_massage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  http: ^1.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sim_card_info: ^1.0.2
  telephony: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0

flutter_icons:
  image_path: "assets/icon_launcher.png"
  android: true
  ios: true
flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/

